name: Integration Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install bun
        uses: jdx/mise-action@v2
        with:
          cache: true
          experimental: true
          mise_toml: |
            [settings.npm]
            bun = true

            [tools]
            bun = "latest"
            "npm:github-actions-ctrf" = "latest"
            "npm:junit-to-ctrf" = "latest"
            "npm:node-static" = "latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get bun cache directory
        id: bun-cache-dir
        run: |
          echo "bun-cache-dir=$(bun pm cache)" >> $GITHUB_OUTPUT
        shell: bash

      - uses: actions/cache@v4
        name: Bun cache
        with:
          path: ${{ steps.bun-cache-dir.outputs.bun-cache-dir }}
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}

      - name: Bun install and build
        run: |
          bun install
          bun run build

      - uses: actions/cache@v4
        name: Playwright cache
        with:
          path: |
            ~/.cache/ms-playwright/
          key: ${{ runner.os }}-playwright-${{ hashFiles('node_modules/playwright/package.json') }}

      - run: bun pw:install --with-deps
        name: Install Playwright dependencies

      - run: bun test:pw
        name: Run Playwright tests

      - name: Report Test Results
        run: |
          junit-to-ctrf test_results.xml -o ctrf/test_results.json
          github-actions-ctrf ctrf/*.json
        if: always()
